# Generated by Django 4.2.5 on 2024-01-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_notification_receiver_alter_notification_groupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
