# Generated by Django 4.2.5 on 2024-01-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_messagemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
