# Generated by Django 4.2.5 on 2023-11-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aboutme',
            field=models.CharField(blank=True, default='About me', max_length=100),
        ),
    ]
