# Generated by Django 4.2.5 on 2023-11-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, default=80, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_avatar', to='core.media'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
